### ISSUE TITLE
Rebase (and update) image ?

### ISSUE THREAD

**Issue by nsteinmetz** [hypriot/rpi-alpine#2]
Hi,

As this image is a dependance of `hypriot/rpi-traefik` and is not updated on a regular basis, should we rebase this image on https://hub.docker.com/r/arm32v6/alpine/ ?

```
FROM arm32v6/alpine:3.6
COPY tmp/qemu-arm-static /usr/bin/qemu-arm-static
```

Is the hack of qemu still required? I remember a issue where you said you expected a newer kernel to get rid of it. Is it the case with Alpine 3.6?

There is no `alpine` image for `arm32v7` (yet).

Thanks,
Nicolas

**Comment by StefanScherer** [comment]
With kernel 4.9 in TravisCI we can remove the qemu binary. They still are at 4.4.

**Comment by nsteinmetz** [comment]
So it means that `rpi-alpine` is no longer required for `rpi-traefik' too and that we can rebase all images on `arm32v6/alpine:3.6` instead ?

**Comment by StefanScherer** [comment]
We can update this Dockerfile to `FROM arm32v6/alpine:3.6`, build and push a 3.6 of hypriot/rpi-alpine and then use it for rpi-traefik etc.
Once Travis offers Kernel 4.9 we can directly switch to arm32v6/alpine.

**Comment by nsteinmetz** [comment]
Ok clear, could you add me as collaborator here too so that I can update the Dockerfile directly ?

**Comment by StefanScherer** [comment]
Sure :-)

**Comment by nsteinmetz** [comment]
For the record, I have to revert qemu update and stick to 2.6.0 release.

I assume that `docker run --rm --privileged multiarch/qemu-user-static:register --reset` leads to an old image (not updated for 6 months now) and so not compatible with earlier version of qemu :-/

So we have a `rpi-alpine:3.6` release and so is `rpi-traefik` too.
